- name: Get software to install pip.
  apt: "name={{ item }} state=installed"
  with_items:
    - python-setuptools
    - python-dev
    - build-essential

- name: Get if pip is already installed variable
  shell: which pip
  register: which_result
  ignore_errors: true

- debug:
    msg: "Jessie value is  {{ which_result }} and"


- name: Install pip via easy install
  command: easy_install pip
  become: true
  when: which_result.stdout == ''

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ pip_install_packages }}"