- name: Get software to install pip.
  apt: "name={{ item }} state=installed"
  with_items:
    - python-setuptools
    - python-dev
    - build-essential


- name: install pip via easy install
  easy_install:
    name: pip
    state: latest

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ pip_install_packages }}"