---

- name: get linux distro
  shell:  cat /etc/*-release | grep VERSION | grep jessie
  register: jessie

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- debug:
    msg: "Jessie value is  {{ jessie }} and"


#- fail: msg="Can't move on, we need to this 'ansible_distribution' to know which version of Debian are we."
#  when: ansible_distribution is undefined

- import_tasks: debian.yml
  #when: jessie.stdout_lines != ''
  when:
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "8"